### ISSUE TITLE
Villagers sometimes getting stuck or not moving to goal

### ISSUE THREAD

**Issue by waffel183** [PvB-Groep-1/DevDorp#37]
Sometimes the villagers do not move to their goal, or moving in a completely different direction.
This is unwanted behaviour.

This bug is not present when there is only 1 villager in the scene.

**Comment by empireboy** [comment]
I finally found out why this happends. You save references like the NavMeshAgent into the states. But you need to understand that there is only one of each state, so one Wandering State for example. All Villagers use the same Wandering State. This means that when you set the _navMeshAgent inside the Wandering State, it will be set in the actual Wandering State where there is only one of. So every Villager with the Wandering State uses the same _navMeshAgent variable.

This is why you need to use the StateController.navMeshAgent to get the NavMeshAgent for the current Villager instead of saving it into the sate.

A solution would be to remove the _navMeshAgent and _targetDestination variable in all your Actions and Decision and use the ones from sc.navMeshAgent and sc.targetDestination in your methods where you get the current sc (StateController).
